### ISSUE TITLE
After opening an app from the list of apps, it gets stuck "Please wait.."

### ISSUE THREAD

**Issue by yashali** [ideonate/streamlit-launchpad#11]
Hi, as per the docs : as per streamlit’s official knowledge-base/deploy/remote-start blog

I can see the headers : from the developer tools for the request : wss://myorigin/streamlit/stream33.py/stream

Host: myorigin
Origin: myorigin
Pragma: no-cache
Sec-Websocket-Extensions: permessage-deflate; client_max_window_bits
Sec-Websocket-Key: hB0DcabcabcabcQ8BoVDAvg==
Sec-Websocket-Protocol: streamlit
Sec-Websocket-Version: 13
Trusted_user: username
Upgrade: websocket

I use streamlit-launchpad to host some files. Since I use a linux container to deploy my app with nginx ingress controller & ingress on a cloud k8s cluster, the command is:

[github.com](https://github.com/ideonate/streamlit-launchpad/blob/master/launchpad/main.py#L108)
[ideonate/streamlit-launchpad/blob/master/launchpad/main.py#L108](https://github.com/ideonate/streamlit-launchpad/blob/master/launchpad/main.py#L108)

I still get the same “Please wait” screen…

Here are my pod logs:

INCOMING URL: st-allowed-message-origins

GET : localhost:8500 / st-allowed-message-origins

{‘X-Request-Id’: ‘da788e351b3ebadce’, ‘X-Real-Ip’: ‘10.2.133.228’, ‘X-Forwarded-For’: ‘10.2.133.228’, ‘X-Forwarded-Host’: ‘myorigin’, ‘X-Forwarded-Port’: ‘443’, ‘X-Forwarded-Proto’: ‘https’, ‘X-Forwarded-Scheme’: ‘https’, ‘X-Scheme’: ‘https’, ‘X-Original-Forwarded-For’: ‘10.2.133.228:50598’, ‘X-Original-Url’: ‘/streamlit/stream33.py/st-allowed-message-origins’, ‘X-Appgw-Trace-Id’: ‘e925f57d275a1’, ‘X-Original-Host’: ‘[myorigin](http://myorigin/)’, ‘Cache-Control’: ‘no-cache’, ‘Sec-Ch-Ua’: ‘“Not.A/Brand”;v=“8”, “Chromium”;v=“114”, “Google Chrome”;v=“114”’, ‘Accept’: ‘application/json, text/plain, /’, ‘Sec-Ch-Ua-Mobile’: ‘?0’, ‘User-Agent’: ‘Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36’, ‘Sec-Ch-Ua-Platform’: ‘“Windows”’, ‘Sec-Fetch-Dest’: ‘empty’, ‘Referer’: ‘myorigin/streamlit/stream33.py/’, ‘Accept-Language’: ‘en-US,en;q=0.9’, ‘Cookie’: ‘appgwcookieCORS=0a153a090a; appgwcookie=0a153a012a960ca90a; _oauth2_proxy_test_auth0=ghJaeI=’, ‘Access-Control-Allow-Origin’: ‘true’}

HTTPResponse(_body=None,_error_is_response_code=False,buffer=<_io.BytesIO object at 0x7fa15e0>,code=200,effective_url=‘myorigin/st-allowed-message-origins’,error=None,headers=<tornado.httputil.HTTPHeaders object at 0x7fe8bd60>,reason=‘OK’,request=<tornado.httpclient.HTTPRequest object at 0x7fe8d90>,request_time=0.0029108509766,start_time=1686247682.466749,time_info={})

Server: TornadoServer/6.1

Content-Type: application/json; charset=UTF-8

Date: Thu, 08 Jun 2023 GMT

Cache-Control: no-cache

Access-Control-Allow-Origin: *

Etag: “30036018d31a0b1eaba”

Content-Length: 503

Vary: Accept-Encoding

Connection: close

200

response body

WEBSOCKET OPENING ON ws://localhost:8500/stream

INCOMING URL: st-allowed-message-origins

… this keeps repeating

**Comment by danlester** [comment]
To be honest, I struggle to believe that Streamlit doesn't have a better native way to achieve what's needed now (i.e. without streamlit-launchpad). This codebase was all from a long time ago. It could be worth reading through their forums/issues to see what's recommended for 'multipage apps' these days, or ask them directly.
