### ISSUE TITLE
Errors when launching the streamlit apps

### ISSUE THREAD

**Issue by rsheftel** [ideonate/streamlit-launchpad#3]
First thank you for this cool project. I am having a problem getting to work. Note that all of the underlying streamlit apps work find when run from the CLI. 

I issue the following command to launch the streamlit-launchpad and that works:

![image](https://user-images.githubusercontent.com/11539619/82758295-ad466500-9db3-11ea-98cc-feeba53467c4.png)

It shows the web page launcher:
![image](https://user-images.githubusercontent.com/11539619/82758315-cc44f700-9db3-11ea-8d91-2659ff91832e.png)

But when I click on any app to run I get this error: (browser)
![image](https://user-images.githubusercontent.com/11539619/82758329-e1ba2100-9db3-11ea-88b8-bdccc7af61f5.png)

The command line:
![image](https://user-images.githubusercontent.com/11539619/82758337-eda5e300-9db3-11ea-862c-92ece47eb9dd.png)

I am using tornoda v5.1.1

Any help is appreciated. thanks!

**Comment by danlester** [comment]
Thank you for your interest!

Unfortunately, a component of Tornado does not work under Windows. In particular, [this code](https://github.com/ideonate/streamlit-launchpad/blob/master/launchpad/main.py#L79) uses [tornado.process.Subprocess](https://www.tornadoweb.org/en/stable/process.html#tornado.process.Subprocess). The documentation there says it doesn't work on Windows.

If easy for you to run in a Docker container, that should work.

Or it should be possible to modify the code to run on Windows (probably just remove the line 79 that I linked above), but it wouldn't tidy up the processes when they finish.

Maybe we can see if these ideas help you, and then I'll add a note for Windows users on the readme.

**Comment by rsheftel** [comment]
Oh, I completely missed the part about not working on Windows. Thanks again for a great package

**Comment by rsheftel** [comment]
FYI, I submitted a new PR #8 based on your suggestions. tested on my Windows machine and it works. Thanks!

**Comment by danlester** [comment]
Thank you very much - I've released a version 0.0.11!

I still think Streamlit needs to build in this 'launchpad' functionality natively. I can't believe they haven't yet really!

**Comment by rsheftel** [comment]
I completely agree!

Can you push the v0.11 to pypi, thanks!

**Comment by danlester** [comment]
Oh yes, I missed that step... it's on there now.
