### ISSUE TITLE
OSError: [Errno 99] Cannot assign requested address when starting Dockerized web app

### ISSUE THREAD

**Issue by ohjho** [ideonate/streamlit-launchpad#6]
I keep bumping into [this issue](https://medium.com/@simicode/oserror-errno-99-cannot-assign-requested-address-when-starting-dockerized-web-app-54c11f7041ea) occasionally. Is it possible to expose an optional arg for setting the app's root ip address? (i.e. "0.0.0.0" as oppose to "localhost")

**Comment by danlester** [comment]
It should be possible to do that, but I think it's unlikely it will solve your problem. If it normally works for you, then it seems likely that it can access the port via 'localhost' as much as it could via 0.0.0.0. The first suggestion in your link is perhaps the problem - that other processes are already running on the same port.

So I think it would be best to try to understand if that's the case, and exactly what else is already running.
